import { Paint } from '../types';

// A comprehensive offline dataset of miniature paints
export const MOCK_PAINTS: Paint[] = [
  // Citadel - Base
  { id: 'c_base_01', name: 'Macragge Blue', brand: 'Citadel', paintType: 'Base', colorHex: '#0f3d7c' },
  { id: 'c_base_01b', name: 'Kantor Blue', brand: 'Citadel', paintType: 'Base', colorHex: '#02134e' },
  { id: 'c_base_01c', name: 'Caledor Sky', brand: 'Citadel', paintType: 'Base', colorHex: '#366d98' },
  { id: 'c_base_01d', name: 'Stegadon Scale Green', brand: 'Citadel', paintType: 'Base', colorHex: '#06455d' },
  { id: 'c_base_01e', name: 'Sotek Green', brand: 'Citadel', paintType: 'Base', colorHex: '#0b6371' },
  { id: 'c_base_01f', name: 'Thousand Sons Blue', brand: 'Citadel', paintType: 'Base', colorHex: '#18aabf' },
  { id: 'c_base_01g', name: 'Night Lords Blue', brand: 'Citadel', paintType: 'Base', colorHex: '#002c4f' },
  { id: 'c_base_02', name: 'Mephiston Red', brand: 'Citadel', paintType: 'Base', colorHex: '#9a1115' },
  { id: 'c_base_03', name: 'Abaddon Black', brand: 'Citadel', paintType: 'Base', colorHex: '#232527' },
  { id: 'c_base_04', name: 'Corax White', brand: 'Citadel', paintType: 'Base', colorHex: '#ffffff' },
  { id: 'c_base_05', name: 'Retributor Armour', brand: 'Citadel', paintType: 'Base', colorHex: '#c7b070' },
  { id: 'c_base_06', name: 'Leadbelcher', brand: 'Citadel', paintType: 'Base', colorHex: '#868c8f' },
  { id: 'c_base_07', name: 'Averland Sunset', brand: 'Citadel', paintType: 'Base', colorHex: '#fbb81c' },
  { id: 'c_base_08', name: 'Caliban Green', brand: 'Citadel', paintType: 'Base', colorHex: '#003d15' },
  { id: 'c_base_09', name: 'Kantor Blue', brand: 'Citadel', paintType: 'Base', colorHex: '#02134e' },
  { id: 'c_base_10', name: 'Khorne Red', brand: 'Citadel', paintType: 'Base', colorHex: '#650001' },
  { id: 'c_base_11', name: 'Mournfang Brown', brand: 'Citadel', paintType: 'Base', colorHex: '#640f0b' },
  { id: 'c_base_12', name: 'Rakarth Flesh', brand: 'Citadel', paintType: 'Base', colorHex: '#9c998d' },
  { id: 'c_base_13', name: 'Rhinox Hide', brand: 'Citadel', paintType: 'Base', colorHex: '#462f30' },
  { id: 'c_base_14', name: 'Zandri Dust', brand: 'Citadel', paintType: 'Base', colorHex: '#9e915c' },
  { id: 'c_base_15', name: 'Bugmans Glow', brand: 'Citadel', paintType: 'Base', colorHex: '#804c43' },
  { id: 'c_base_16', name: 'Balthasar Gold', brand: 'Citadel', paintType: 'Base', colorHex: '#a47552' },
  { id: 'c_base_17', name: 'Death Guard Green', brand: 'Citadel', paintType: 'Base', colorHex: '#73805b' },
  { id: 'c_base_18', name: 'Jokaero Orange', brand: 'Citadel', paintType: 'Base', colorHex: '#ed3814' },
  { id: 'c_base_19', name: 'Stegadon Scale Green', brand: 'Citadel', paintType: 'Base', colorHex: '#06455d' },
  { id: 'c_base_20', name: 'Incubi Darkness', brand: 'Citadel', paintType: 'Base', colorHex: '#082e32' },
  { id: 'c_base_21', name: 'Waaagh! Flesh', brand: 'Citadel', paintType: 'Base', colorHex: '#0b3b24' },
  { id: 'c_base_22', name: 'Castellan Green', brand: 'Citadel', paintType: 'Base', colorHex: '#314821' },
  { id: 'c_base_23', name: 'Mechanicus Standard Grey', brand: 'Citadel', paintType: 'Base', colorHex: '#39484a' },
  { id: 'c_base_24', name: 'Celestra Grey', brand: 'Citadel', paintType: 'Base', colorHex: '#8fa0a3' },
  
  // Citadel - Shade
  { id: 'c_shade_01', name: 'Nuln Oil', brand: 'Citadel', paintType: 'Shade', colorHex: '#181818' },
  { id: 'c_shade_02', name: 'Agrax Earthshade', brand: 'Citadel', paintType: 'Shade', colorHex: '#3d2b1f' },
  { id: 'c_shade_03', name: 'Reikland Fleshshade', brand: 'Citadel', paintType: 'Shade', colorHex: '#673e2d' },
  { id: 'c_shade_04', name: 'Drakenhof Nightshade', brand: 'Citadel', paintType: 'Shade', colorHex: '#131e3d' },
  { id: 'c_shade_05', name: 'Biel-Tan Green', brand: 'Citadel', paintType: 'Shade', colorHex: '#123927' },
  { id: 'c_shade_06', name: 'Carroburg Crimson', brand: 'Citadel', paintType: 'Shade', colorHex: '#61162d' },
  { id: 'c_shade_07', name: 'Casandora Yellow', brand: 'Citadel', paintType: 'Shade', colorHex: '#d18625' },
  { id: 'c_shade_08', name: 'Druchii Violet', brand: 'Citadel', paintType: 'Shade', colorHex: '#382240' },
  
  // Citadel - Layer
  { id: 'c_layer_01', name: 'Altdorf Guard Blue', brand: 'Citadel', paintType: 'Layer', colorHex: '#2d65a4' },
  { id: 'c_layer_02', name: 'Calgar Blue', brand: 'Citadel', paintType: 'Layer', colorHex: '#4271b1' },
  { id: 'c_layer_02b', name: 'Teclis Blue', brand: 'Citadel', paintType: 'Layer', colorHex: '#3878bd' },
  { id: 'c_layer_02c', name: 'Lothern Blue', brand: 'Citadel', paintType: 'Layer', colorHex: '#33a3d2' },
  { id: 'c_layer_02d', name: 'Hoeth Blue', brand: 'Citadel', paintType: 'Layer', colorHex: '#4c78a4' },
  { id: 'c_layer_02e', name: 'Alaitoc Blue', brand: 'Citadel', paintType: 'Layer', colorHex: '#214e7a' },
  { id: 'c_layer_03', name: 'Evil Sunz Scarlet', brand: 'Citadel', paintType: 'Layer', colorHex: '#c01411' },
  { id: 'c_layer_04', name: 'Wild Rider Red', brand: 'Citadel', paintType: 'Layer', colorHex: '#e82e1b' },
  { id: 'c_layer_05', name: 'Eshin Grey', brand: 'Citadel', paintType: 'Layer', colorHex: '#484b4e' },
  { id: 'c_layer_06', name: 'Dawnstone', brand: 'Citadel', paintType: 'Layer', colorHex: '#697068' },
  { id: 'c_layer_07', name: 'Ironbreaker', brand: 'Citadel', paintType: 'Layer', colorHex: '#939798' },
  { id: 'c_layer_08', name: 'Runefang Steel', brand: 'Citadel', paintType: 'Layer', colorHex: '#aeb3b5' },
  { id: 'c_layer_09', name: 'Yriel Yellow', brand: 'Citadel', paintType: 'Layer', colorHex: '#ffd51b' },
  { id: 'c_layer_10', name: 'Warpstone Glow', brand: 'Citadel', paintType: 'Layer', colorHex: '#18702e' },
  { id: 'c_layer_11', name: 'Moot Green', brand: 'Citadel', paintType: 'Layer', colorHex: '#3da530' },
  { id: 'c_layer_12', name: 'Skrag Brown', brand: 'Citadel', paintType: 'Layer', colorHex: '#8b4806' },
  { id: 'c_layer_13', name: 'Cadian Fleshtone', brand: 'Citadel', paintType: 'Layer', colorHex: '#c47652' },
  { id: 'c_layer_14', name: 'Kislev Flesh', brand: 'Citadel', paintType: 'Layer', colorHex: '#d6a780' },
  { id: 'c_layer_15', name: 'Ushabti Bone', brand: 'Citadel', paintType: 'Layer', colorHex: '#bcad7f' },
  { id: 'c_layer_16', name: 'Screaming Skull', brand: 'Citadel', paintType: 'Layer', colorHex: '#d2c9a5' },
  { id: 'c_layer_17', name: 'Troll Slayer Orange', brand: 'Citadel', paintType: 'Layer', colorHex: '#f36d2d' },
  { id: 'c_layer_18', name: 'Sotek Green', brand: 'Citadel', paintType: 'Layer', colorHex: '#0b6371' },
  
  // Vallejo - Game Color
  { id: 'v_game_01', name: 'Dead White', brand: 'Vallejo', paintType: 'Game Color', colorHex: '#ffffff' },
  { id: 'v_game_02', name: 'Black', brand: 'Vallejo', paintType: 'Game Color', colorHex: '#000000' },
  { id: 'v_game_03', name: 'Ultramarine Blue', brand: 'Vallejo', paintType: 'Game Color', colorHex: '#1d3e8e' },
  { id: 'v_game_04', name: 'Bloody Red', brand: 'Vallejo', paintType: 'Game Color', colorHex: '#d81e28' },
  { id: 'v_game_05', name: 'Goblin Green', brand: 'Vallejo', paintType: 'Game Color', colorHex: '#41924B' },
  { id: 'v_game_06', name: 'Sun Yellow', brand: 'Vallejo', paintType: 'Game Color', colorHex: '#f1cc26' },
  { id: 'v_game_07', name: 'Glorious Gold', brand: 'Vallejo', paintType: 'Game Color', colorHex: '#bd8e34' },
  { id: 'v_game_08', name: 'Gunmetal', brand: 'Vallejo', paintType: 'Game Color', colorHex: '#4f5255' },
  { id: 'v_game_09', name: 'Beasty Brown', brand: 'Vallejo', paintType: 'Game Color', colorHex: '#523725' },
  { id: 'v_game_10', name: 'Leather Brown', brand: 'Vallejo', paintType: 'Game Color', colorHex: '#6c4a2a' },
  { id: 'v_game_11', name: 'Dark Fleshtone', brand: 'Vallejo', paintType: 'Game Color', colorHex: '#5d372c' },
  
  // Vallejo - Model Color
  { id: 'v_model_01', name: 'White', brand: 'Vallejo', paintType: 'Model Color', colorHex: '#ffffff' },
  { id: 'v_model_02', name: 'Black', brand: 'Vallejo', paintType: 'Model Color', colorHex: '#000000' },
  { id: 'v_model_03', name: 'Flat Red', brand: 'Vallejo', paintType: 'Model Color', colorHex: '#b22222' },
  { id: 'v_model_04', name: 'Flat Blue', brand: 'Vallejo', paintType: 'Model Color', colorHex: '#2554c7' },
  { id: 'v_model_05', name: 'Flat Green', brand: 'Vallejo', paintType: 'Model Color', colorHex: '#228b22' },
  { id: 'v_model_06', name: 'Flat Earth', brand: 'Vallejo', paintType: 'Model Color', colorHex: '#936a43' },
  { id: 'v_model_07', name: 'Cork Brown', brand: 'Vallejo', paintType: 'Model Color', colorHex: '#ab7f58' },
  { id: 'v_model_08', name: 'English Uniform', brand: 'Vallejo', paintType: 'Model Color', colorHex: '#685933' },
  { id: 'v_model_09', name: 'Luftwaffe Camo Green', brand: 'Vallejo', paintType: 'Model Color', colorHex: '#464b38' },
];
